version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: quizdb_container
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quizapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizapi_container
    ports:
      - "5045:5045"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5045

volumes:
  postgres_data: